Dev 3.x
syscoin/syscoin pull request #278
Opened 2018-09-07 18:40 UTC by willyko

removes the buffer for asset interest calculation and fixes precision using boost multiprecision

2018-09-07 18:41 UTC, sidhujag submitted a review, later dismissed

2018-09-07 19:00 UTC, Keyare submitted a review, later dismissed

2018-09-07 19:04 UTC, radubcf submitted a review, later dismissed

2018-09-07 19:29 UTC, Keyare submitted a review, later dismissed

2018-09-08 04:20 UTC, sidhujag submitted a review, later dismissed

2018-09-08 04:21 UTC, Keyare submitted a review, later dismissed

2018-09-08 04:22 UTC, jnessbcf requested changes

2018-09-08 04:22 UTC, jnessbcf commented on src/assetallocation.cpp
> +	const cpp_dec_float_50 &nInterestBlockTerm = fUnitTest ? cpp_dec_float_50(ONE_HOUR_IN_BLOCKS) : cpp_dec_float_50(ONE_YEAR_IN_BLOCKS);
Why is there a variable indicating a unit test in the main code base?  What is this regarding?

2018-09-08 04:24 UTC, sidhujag commented on src/assetallocation.cpp
> +	const cpp_dec_float_50 &nInterestBlockTerm = fUnitTest ? cpp_dec_float_50(ONE_HOUR_IN_BLOCKS) : cpp_dec_float_50(ONE_YEAR_IN_BLOCKS);
for unit test functionality.. the code is the same for test and mainchain but shipped without unittest outside of the test suite.

2018-09-08 04:37 UTC, radubcf submitted a review, later dismissed

2018-09-08 05:48 UTC, jnessbcf submitted a review, later dismissed

2018-09-08 13:53 UTC, Keyare approved these changes

2018-09-08 16:37 UTC, sidhujag approved these changes

2018-09-08 16:39 UTC, sidhujag approved these changes

2018-09-08 17:01 UTC, jnessbcf approved these changes

2018-09-08 17:15 UTC, radubcf approved these changes

2018-09-09 05:44 UTC, merged